version: '3.8'

services:
  backend:
    container_name: flask_app
    build: .
    restart: always
    ports:
      - "8000:8000"

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
