"""create migrations and clinic tables

Revision ID: 0cf8a3704c54
Revises: 34e26c284ff4
Create Date: 2025-03-12 21:09:13.034212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf8a3704c54'
down_revision = '34e26c284ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_admins')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index('ix_admins_provider_name')
        batch_op.drop_column('provider_name')

    with op.batch_alter_table('test_orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_test_orders_test_id', type_='foreignkey')
        batch_op.drop_column('test_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_description', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_test_orders_test_description', 'tests', ['test_description'], ['test_id'])

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_name', sa.VARCHAR(length=128), nullable=True))
        batch_op.create_index('ix_admins_provider_name', ['provider_name'], unique=1)

    op.create_table('_alembic_tmp_admins',
    sa.Column('admin_id', sa.INTEGER(), nullable=False),
    sa.Column('is_authenticated', sa.BOOLEAN(), nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    # ### end Alembic commands ###
