"""adding Foreign key

Revision ID: 34e26c284ff4
Revises: 9ed3bd94b001
Create Date: 2025-03-04 00:23:53.160000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e26c284ff4'
down_revision = '9ed3bd94b001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_test_orders_test_id', 'tests', ['test_id'], ['test_id'])
        batch_op.create_foreign_key('fk_test_orders_user_id', 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    with op.batch_alter_table('test_orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_test_orders_test_id', type_='foreignkey')
        batch_op.drop_constraint('fk_test_orders_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('test_id')

    # ### end Alembic commands ###
