"""empty message

Revision ID: 9ed3bd94b001
Revises: 
Create Date: 2025-02-28 20:02:13.671781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed3bd94b001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=128), nullable=True),
    sa.Column('is_authenticated', sa.Boolean(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_provider_name'), ['provider_name'], unique=True)

    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_default'), ['default'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('tests',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=128), nullable=True),
    sa.Column('test_description', sa.String(length=255), nullable=True),
    sa.Column('test_category', sa.String(length=255), nullable=True),
    sa.Column('test_subcategory', sa.String(length=255), nullable=True),
    sa.Column('test_type', sa.String(length=64), nullable=True),
    sa.Column('sample_type', sa.String(length=15), nullable=True),
    sa.Column('turn_around_time', sa.Integer(), nullable=True),
    sa.Column('test_price', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('test_id')
    )
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tests_test_name'), ['test_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_tests_test_price'), ['test_price'], unique=True)

    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['amount'], ['tests.test_price'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('test_orders',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('test_description', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tube_size', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_description'], ['tests.test_id'], ),
    sa.PrimaryKeyConstraint('request_id'),
    sa.UniqueConstraint('location')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_location'), ['location'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_location'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('test_orders')
    op.drop_table('payments')
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tests_test_price'))
        batch_op.drop_index(batch_op.f('ix_tests_test_name'))

    op.drop_table('tests')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_default'))

    op.drop_table('roles')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_provider_name'))

    op.drop_table('admins')
    # ### end Alembic commands ###
