name: Deploy Caremax Hospitals Web Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH into VPS and Deploy
        run: |
          ssh user@your-vps-ip <<EOF
            cd \Desktop\RDC\caremax
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
